### ISSUE TITLE
Thx for this :)

### ISSUE THREAD

**Issue by daxime** [thexhr/isscrolls#11]
I've just discovered Ironsworn and was looking for a tool to manage my games, if I like this game. This is the only downloadable AND working application I've found. I would have liked a graphical interface, but I think it's cool anyway. I've always found CLI programs oddly interesting (Dwarf Fortress before the steam release blow my mind), even though I never use them.

Plus, the fact that it's accessible via SSH could be useful if I get hooked on Ironsworn.

**Comment by thexhr** [comment]
Thanks for your feedback, much appreciated!
