### ISSUE TITLE
error: implicit declaration of function ‘json_object_array_del_idx’

### ISSUE THREAD

**Issue by csrobins03** [thexhr/isscrolls#7]
I'm trying to get this running in Debian on WSL, I've followed the instructions on the main page, but this is what happens when I run make:

***@***:~/isscrolls$ make
cc -O2 -pipe -fdiagnostics-color -Wno-unknown-warning-option -Wpedantic -Wall -Werror-implicit-function-declaration -Wno-format-truncation -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wshadow -Wpointer-arith -Wcast-qual -Wsign-compare -Wswitch-enum -Wunused-parameter -Wuninitialized -Wformat-security -Wformat-overflow=2 -I/usr/local/include `pkg-config --cflags json-c` -o character.o -c character.c
character.c: In function ‘save_character’:
character.c:611:5: error: implicit declaration of function ‘json_object_array_del_idx’; did you mean ‘json_object_array_get_idx’? [-Werror=implicit-function-declaration]
     json_object_array_del_idx(items, i, 1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~
     json_object_array_get_idx
character.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1: some warnings being treated as errors
make: *** [Makefile:44: character.o] Error 1

**Comment by thexhr** [comment]
Hi,

in order to diagnose the error, can you please provide the following information:

- Exact version of Debian
- Version of json-c you use (do you installed it as a package or via source?)
- Output of `cc --version`

Thanks

**Comment by csrobins03** [comment]
$ cat /etc/debian_version
10.13

$ apt list libjson-c*
Listing... Done
libjson-c-dev/oldstable,oldstable,now 0.12.1+ds-2+deb10u1 amd64 [installed]
libjson-c-doc/oldstable,oldstable 0.12.1+ds-2+deb10u1 all
libjson-c3/oldstable,oldstable,now 0.12.1+ds-2+deb10u1 amd64 [installed,automatic]

$ cc --version
cc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by csrobins03** [comment]
Upgrading to Debian 11 (and therefore libjson-c version 15) has solved the problem as I now meet them minimum requirements. Thanks.

**Comment by thexhr** [comment]
Thanks for upgrading and resolving the ticket!
