### ISSUE TITLE
Feature Request: Implement Failure Track

### ISSUE THREAD

**Issue by csrobins03** [thexhr/isscrolls#8]
One thing I always have trouble remembering to do is record my misses on the failure track. I noticed that Mark Your Failure and Learn From Your Failures are listed in the initial commit of moves. In order of importance, I think it would very helpful to have a failure track which:

1. Can be adjusted manually like the bond track
2. Reports failure track progress when the character info is printed
3. Automatically tracks misses on moves and progress moves
4. Automatically applies new experience and clears the progress per the Learn From Your Failures move

**Comment by thexhr** [comment]
I just pushed a series of commits to master:

- Failure track for characters (visible in the print screen when failures are > 0)
- Possibility to increase/decrease _failure_
- And your Numbers 3 + 4

Please checkout latest master, rebuild and test. In the next days I will also commit the missing man page changes.

**Comment by csrobins03** [comment]
Wow, that was fast. Thanks. It looks like it's working great. I like the "You didn't fail enough, yet!" when you have less than 6.0

The only issue is a small one, when you Learn From Your Failures on a **miss**, it reports increasing failure by 0.5 because you failed a progress move, but then it silently clears the track as per the move.

Perhaps the resetting of the track should be printed in the output so there is no confusion.

**Comment by thexhr** [comment]
I pushed a commit that fixes the confusing output on a miss of the "learn from your failure" move.

**Comment by csrobins03** [comment]
Looks to be working great. Thanks
